<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <AssemblyName>neutral.tactical.laser</AssemblyName>
    <RootNamespace>TLS</RootNamespace>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <LangVersion>7.3</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="Extra\tls.commands.qol" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="BepInEx.Core" Version="5.4.21" />
    <PackageReference Include="HarmonyX" Version="2.10.1" />
    <PackageReference Include="UnityEngine.Modules" Version="2021.3.17" IncludeAssets="compile" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="Assembly-CSharp">
      <HintPath>..\..\COMPILER_HERE\game\Assembly-CSharp.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="Mirage">
      <HintPath>..\..\COMPILER_HERE\game\Mirage.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
